### ISSUE TITLE
Sensor Graphs - Local Virtuoso Data Store

### ISSUE THREAD

**Issue by premjayaraman** [OpenIotOrg/openiot#40] opened 2013-12-04 01:10 UTC
The ObsContant.java in org.openiot.lsm.utils defines the following

public final static String sensormasherMetadataGraphURI = "http://lsm.deri.ie/OpenIoT/sensormeta#";
public final static String sensormasherDataGraphURI = "http://lsm.deri.ie/OpenIoT/sensordata#";
public final static String sensormasherOntologyURI = "http://lsm.deri.ie/ont/lsm.owl#";
public final static String SSNOntolotyURI ="http://purl.oclc.org/NET/ssnx/ssn#";
public final static String ServerHost = "http://localhost:8081/lsm-light.server/";
public static String TEMPERATURE = "http://lsm.deri.ie/ont/lsm.owl#AirTemperature";
public static String HUMIDITY = "http://lsm.deri.ie/ont/lsm.owl#AtmosphereHumidity";
public static String WINDCHILL = "http://lsm.deri.ie/ont/lsm.owl#WindChill";
public static String WINDSPEED = "http://lsm.deri.ie/ont/lsm.owl#WindSpeed";
public static String PRESSURE = "http://lsm.deri.ie/ont/lsm.owl#AtmospherePressure";
public static String VISIBILITY = "http://lsm.deri.ie/ont/lsm.owl#AtmosphereVisibility";
public static String STATUS = "http://lsm.deri.ie/ont/lsm.owl#Status";
public static String CAMERA_IMAGE = "http://lsm.deri.ie/ont/lsm.owl#WebcamSnapShot";

As it can be noted, except for the server, all the sensorMetadata and sensorDatagraph points to lsm.deri.ie.

Should this not be replaced with a local virtuoso instance? 

If so how do we setup the local virtuoso instance for OpenIoT. 

More specifically,
• How do we create the graph database for sensorMetaData and sensorData?

There is no documentation related to creation of graph tables corresponding to OpenIoT ontology on virtuoso available.

**Comment by hylkevds** [comment] 2013-12-05 09:22
Actually, they should point to the OpenIoT ontology, or the "parent" ontology that was used. I doubt we're the first ones to define AirTemperature.

In any case, the urls should return something when they are accessed. Pointing to a definition that can not be accessed defeats the point.

As for that last question, that is a duplicate of #3

**Comment by jpcik** [comment] 2013-12-05 09:46
Yes, as it is pointed out, there are vocabularies that define properties like 'air temperature'. For example people from CSIRO defined many of these terms for a use case in this ontology:

http://www.w3.org/2005/Incubator/ssn/ssnx/cf/cf-property.owl

http://www.w3.org/2005/Incubator/ssn/wiki/Agriculture_Meteorology_Sensor_Network

**Comment by premjayaraman** [comment] 2013-12-05 11:11
Hi Hylke

Thanks for pointing it out. yes as jean mentioned most of the definition is in the ssn ontology. 

With lsm I missed #3. I will merge my request with #3.

cheers

**Closed as completed** 2014-03-17 10:05 UTC
Labels: bug
